services:
  - type: web
    name: expense-backend
    env: node
    
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 7000

  - type: web
    name: expense-frontend
    env: static
    
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build